# ribonanzanet.yaml

model:
  class_path: lib.training.modules.finetuning.FinetuningModuleDenseHead
  init_args:
    model:
      class_path: pretrained.ribonanzanet.RibonanzaNet
    out_size: 2
    pooling:
      type: 'mean'
      dim: -2
      nonlinearity: exp
    objectives:
      loss:
        class_path: lib.training.losses.LogMSELoss
      absolute_error:
        class_path: torch.nn.L1Loss
      relative_error:
        class_path: torchmetrics.MeanAbsolutePercentageError

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001

data:
  batch_size: 64
  input_variables:
    - sequence_embeddings


